package team3;
import java.util.*;
import java.sql.*;
 // Data Access Object/Operation
public class UserDao {
	
	/*
	private static Connection getConnection(){  
        Connection con = null;  
        try{  
            Class.forName("com.mysql.jdbc.Driver");  
            con=DriverManager.getConnection("jdbc:mysql://localhost/sakila?useSSL=false", "root", "sesame");  
        }
        catch(Exception e){
        	System.out.println(e);
    	}  
        return con;  
    } 
    */
    
	public static int create(User u){  
        int status = 0;  
        try{  
            Connection con = DBLink.getConnection();  
            PreparedStatement ps = con.prepareStatement(  
                         "insert into userteam3(accountId,username,isLoggedIn) values (?,?,?)");  
            //ps.setInt(1,u.getId()); // auto-generated by DB
            ps.setInt(1,u.getAccountId()); 
            ps.setString(2,u.getUsername());  
            ps.setBoolean(3,u.isLoggedIn());   
              
            status = ps.executeUpdate();  
              
            con.close();  
        }catch(Exception ex){ex.printStackTrace();}  
          
        return status;  
    }  
    
    public static int update(User u){  
        int status = 0;  
        try{  
            Connection con = DBLink.getConnection();  
            PreparedStatement ps = con.prepareStatement(  
                         "update userteam3 set accountId=?,username=?,isLoggedIn=? where id=?");  
            ps.setInt(1,u.getAccountId()); 
            ps.setString(2,u.getUsername());  
            ps.setBoolean(3,u.isLoggedIn());  
            ps.setInt(4, u.getId());
              
            status = ps.executeUpdate();  
              
            con.close();  
        }
        catch(Exception ex){
        	ex.printStackTrace();
        }  
          
        return status;  
    }  
    
    public static int delete(User u){  
        int status = 0;  
        
        try{  
            Connection con = DBLink.getConnection();  
            PreparedStatement ps = con.prepareStatement("delete from userteam3 where id=?");  
            ps.setInt(1,u.getId());  
            
            status=ps.executeUpdate();  
              
            con.close();  
        }
        catch(Exception e){
        	e.printStackTrace();
    	}  
          
        return status;  
    }  
    
    public static User getUserById(int id){  
        User u = new User();  
          
        try{  
            Connection con = DBLink.getConnection();  
            PreparedStatement ps = con.prepareStatement("select * from userteam3 where id=?");  
            ps.setInt(1,id);  
            
            ResultSet rs = ps.executeQuery();  
            
            if(rs.next()){  
            	u.setId(rs.getInt(1));  
                u.setAccountId(rs.getInt(2)); 
                u.setUsername(rs.getString(3)); 
                u.setFavoritesList(FavoritesListDao.getFavoritesListByUserId(u.getId()).getMovieIdList());
                //u.setQueue(QueueDao.getQueueByUserId(u.getId()).getMovieIdList());
                u.setLoggedIn(rs.getBoolean(4)); 
            }  
            con.close();  
        }
        catch(Exception ex){
        	ex.printStackTrace();
    	}  
          
        return u;  
    }  
    
    public static List<User> getUsersForAccount(int accountId){  
        List<User> list = new ArrayList<User>(); 
          
        try{  
            Connection con = DBLink.getConnection();  
            PreparedStatement ps = con.prepareStatement("select * from userteam3 where accountId=? order by id asc");  
            ps.setInt(1,accountId);  
            
            ResultSet rs = ps.executeQuery();  
            
            while(rs.next()){  
            	User u = new User();
            	u.setId(rs.getInt(1));  
                u.setAccountId(rs.getInt(2)); 
                u.setUsername(rs.getString(3)); 
                u.setFavoritesList(FavoritesListDao.getFavoritesListByUserId(u.getId()).getMovieIdList());
                //u.setQueue(QueueDao.getQueueByUserId(u.getId()).getMovieIdList());
                u.setLoggedIn(rs.getBoolean(4)); 
                list.add(u);
            }  
            con.close();  
        }
        catch(Exception ex){
        	ex.printStackTrace();
    	}  
          
        return list;  
    }  
    
    /*
    public static List<User> getAllUsers(){  
        List<User> list=new ArrayList<User>();  
          
        try{  
            Connection con=UserDao.getConnection();  
            PreparedStatement ps=con.prepareStatement("select * from user");  
            ResultSet rs=ps.executeQuery();  
            while(rs.next()){  
                User u = new User(); 
                
                u.setId(rs.getInt(1));  
                u.setAccountId(rs.getInt(2)); 
                u.setUsername(rs.getString(3)); 
                u.setFavoritesList(FavoritesListDao.getFavoritesListByUserId(u.getId()).getMovieIdList());  
                u.setLoggedIn(rs.getBoolean(4)); 

                list.add(u);  
            }  
            con.close();  
        }catch(Exception e){
        	e.printStackTrace();
    	}  
          
        return list;  
    }  
    */
}
